# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - nxquik

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: yarn install, build, and test
        run: |
          echo ${{ secrets.AUTH0_SECRET }}
          echo ${{ secrets.AUTH0_BASE_URL }}
          echo ${{ secrets.AUTH0_ISSUER_BASE_URL }}
          echo ${{ secrets.AUTH0_CLIENT_ID }}
          echo ${{ secrets.AUTH0_CLIENT_SECRET }}
          echo ${{ secrets.AUTH0_AUDIENCE }}
          echo ${{ secrets.AUTH0_SCOPE }}
          yarn install --frozen-lockfile
          yarn build
          mv public .next/standalone/public
          mv .next/static .next/standalone/.next/static
        env:
          AUTH0_SECRET: ${{ secrets.AUTH0_SECRET }}
          AUTH0_BASE_URL: ${{ secrets.AUTH0_BASE_URL }}
          AUTH0_ISSUER_BASE_URL: ${{ secrets.AUTH0_ISSUER_BASE_URL }}
          AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
          AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
          AUTH0_SCOPE: ${{ secrets.AUTH0_SCOPE }}

          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          NEXTAUTH_SECRET: ${{ secrets.AUTH0_SECRET }}

      - name: Zip artifact for deployment
        run: zip -r next.zip .next/standalone/* .next/standalone/.next

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: nxquik-app
          path: next.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: nxquik-app

      - name: unzip artifact for deployment
        run: |
          unzip next.zip
          rm next.zip

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'nxquik'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_85DE48302BF445D7BD0360B6FB5E8A06 }}
          package: ./.next/standalone
